---
# Debian specific installation tasks

- name: Set architecture mapping
  set_fact:
    arch_mapping:
      x86_64: "amd64"
      aarch64: "arm64"
      armv7l: "armhf"

- name: Set package version suffix for x86_64
  set_fact:
    version_suffix: "-1"
  when: ansible_architecture == "x86_64"

- name: Set package version suffix for other architectures
  set_fact:
    version_suffix: ""
  when: ansible_architecture != "x86_64"

- name: Set architecture for package
  set_fact:
    pkg_arch: "{{ arch_mapping[ansible_architecture] | default('amd64') }}"

- name: Check if prompt-color-tool is already installed
  command: dpkg-query -W prompt-color-tool
  register: pkg_check
  failed_when: false
  changed_when: false

- name: Download prompt-color-tool Debian package
  get_url:
    url: "https://github.com/pridkett/prompt-color-tool/releases/download/v{{ prompt_color_tool_version }}/prompt-color-tool_{{ prompt_color_tool_version }}{{ version_suffix }}_{{ pkg_arch }}.deb"
    dest: "/tmp/prompt-color-tool_{{ prompt_color_tool_version }}_{{ pkg_arch }}.deb"
    mode: '0644'
  when: pkg_check.rc != 0

- name: Install prompt-color-tool Debian package
  become: true
  apt:
    deb: "/tmp/prompt-color-tool_{{ prompt_color_tool_version }}_{{ pkg_arch }}.deb"
    state: present
  when: pkg_check.rc != 0

- name: Clean up temporary files
  file:
    path: "/tmp/prompt-color-tool_{{ prompt_color_tool_version }}_{{ pkg_arch }}.deb"
    state: absent
  when: pkg_check.rc != 0
