---
galaxy_info:
  author: Your Name
  description: Role to install prompt-color-tool utility
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - utility
    - tools

dependencies: []
