---
# MacOS specific installation tasks

- name: Ensure Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Fail if Homebrew is not installed
  fail:
    msg: "Homebrew is required but not installed. Please install Homebrew first."
  when: not homebrew_check.stat.exists

- name: Add pridkett/prompt-color-tool tap
  homebrew_tap:
    name: pridkett/prompt-color-tool
    state: present

- name: Install prompt-color-tool via Homebrew
  homebrew:
    name: pridkett/prompt-color-tool/prompt-color-tool
    state: present
