---
# MacOS specific installation tasks

- name: Ensure Homebrew is installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Fail if Homebrew is not installed
  fail:
    msg: "Homebrew is required but not installed. Please install Homebrew first."
  when: not homebrew_check.stat.exists

- name: Install prompt-color-tool via Homebrew
  homebrew:
    name: prompt-color-tool
    state: present
    version: "{{ prompt_color_tool_version }}"
  register: brew_install
  ignore_errors: true

- name: Install prompt-color-tool via Homebrew cask if formula not available
  homebrew_cask:
    name: prompt-color-tool
    state: present
  when: brew_install is failed
